### ISSUE TITLE
Maru how to start LXC?

### ISSUE THREAD

**Issue by Aloento** [maruos/platform_external_lxc#4]
I tried to read through all the code except for the "lxc-start" found in the vendor, and I did not find other places to call LXC.
Please enlighten me.

**Comment by Aloento** [comment]
Since Android does not have shared memory, I can not find the shared memory configuration file from the kernel, so I found LXC and wanted to learn from Maru.
I also found the android dedicated to the memory shared library.
In chroot need to use this:
env LD_PRELOAD="/path/to/libandroid-shmem.so" linux_command

**Comment by Aloento** [comment]
@pdsouza

**Comment by pdsouza** [comment]
Hi @soarteam, nice to hear from you again! 

There are two ways to start LXC on Maru:
1. Use the `lxc-start` binary, example [here](https://groups.google.com/d/msg/maru-os-dev/3negNBhQCu4/55XBPxn-AQAJ)
2. Link against liblxc.so and use the API defined in [lxccontainer.h](https://github.com/maruos/platform_external_lxc/blob/master/src/lxc/lxccontainer.h)

Let me know if you need further clarification, happy to help.

**Comment by Aloento** [comment]
Saying, there is the idea of ​​going to Android O?
I think we should try to write a wiki, let us know how to create a Linux image of their own, so that can not be limited to Debian.
I guess the majority of people use Maru for development and debugging anytime, anywhere, because phones are always better than raspberry.
If you need help, I can always provide, I use Nexus 5X.
I think, with this wiki, we can create a mirror market, you can submit your own Linux system, Maru is no longer built, what you need to download.

**Comment by Aloento** [comment]
Then I learned to use "libandroid-shmem" again. So that I can easily enter a full Linux system with chroot, even includes shared memory and I can run PostgreSQL.

**Comment by pdsouza** [comment]
I think that's a great idea to let others know how to build their own Linux images. The main [Maru wiki](https://github.com/maruos/maruos/wiki) is open for editing so feel free to start creating a page there if you would like. I can start setting that up when I get some free time too.

If you're interested in how the official images are built, please see https://github.com/maruos/blueprints. The Linux image builds are completely automated and allows anyone to create a plugin (called a "blueprint") for any distribution. You can see the default Debian blueprint here: https://github.com/maruos/blueprints/tree/master/blueprint/debian.

Android O would be great although Maru still hasn't moved to N officially 😢 . We have experimental builds for the 5X on N on the `nougat-mr2-release` branch so you could try building that and testing if you would like to help out! Hopefully I will be able to get automated builds going for N which will help us speed up development and testing.

**Comment by Aloento** [comment]
Okay, I'm going to start building a wiki, thanks Maru!
